package com.hemebiotech.writer;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Map;

public class WriteSymptomsInFile implements ISymptomsWriter {

    /**
     * @see WriteSymptomsInFile#WriteInFile()
     * @see com.hemebiotech.launcher.AnalyticsCounterLauncher
     */
    private Map<String, Integer> occurrences;
    private String filepath;
    private String filename;
    /**
     *
     * @param filepath indicate the path to the file generated by the FileWriter
     * @param filename indicate the name of the file generated by the FileWriter
     * @param occurrences, the LinkedHashSet that contains the symptoms in the correct format
     */
    public WriteSymptomsInFile (Map<String, Integer> occurrences, String filepath, String filename) {
        this.filepath  = filepath;
        this.filename = filename;
        this.occurrences = occurrences;
    }

    /**
     * We create a writer with the FileWriter object and indicate where the wile will be created and his name
     * We take the the LinkedHashSet fill in the ReformatSymptomsData class and put his content into a file
     * @see WriteSymptomsInFile#occurrences
     */
    @Override
    public void WriteInFile() throws IOException {
        FileWriter writer = null;
        try {
            writer = new FileWriter(new File(filepath, filename));
            FileWriter finalWriter = writer;
            occurrences.forEach((s, i) -> {
                try {
                    finalWriter.write(s.toLowerCase() + ": " + i + "\n");
                } catch (IOException e) {
                    e.printStackTrace();
                }
            });
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            if (writer != null) {
                writer.close();
            }
        }
    }
}